version: '3.8'

services:
  app:
    build: .
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    networks:
      - app-network
    restart: always


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Ollama API port exposed
    networks:
      - app-network


networks:
  app-network: